"""Configuration file parsing and management"""

import os
from pathlib import Path
from typing import Dict, Any, Optional
from dotenv import dotenv_values
import yaml

from envman.utils.exceptions import ConfigurationError


class ConfigService:
    """Service for reading and writing configuration files"""
    
    @staticmethod
    def parse_env_file(env_path: Path) -> Dict[str, Any]:
        """Parse .env file and return configuration dictionary"""
        if not env_path.exists():
            raise ConfigurationError(f"Environment file not found: {env_path}")
        
        try:
            config = dotenv_values(env_path)
            return {k: v for k, v in config.items() if v is not None}
        except Exception as e:
            raise ConfigurationError(f"Failed to parse {env_path}: {e}")
    
    @staticmethod
    def parse_docker_compose(compose_path: Path) -> Dict[str, Any]:
        """Parse docker-compose.yml file"""
        if not compose_path.exists():
            raise ConfigurationError(f"Docker compose file not found: {compose_path}")
        
        try:
            with open(compose_path, 'r') as f:
                return yaml.safe_load(f)
        except Exception as e:
            raise ConfigurationError(f"Failed to parse {compose_path}: {e}")
    
    @staticmethod
    def write_env_file(env_path: Path, config: Dict[str, Any], backup: bool = True) -> None:
        """Write configuration to .env file"""
        if backup and env_path.exists():
            backup_path = env_path.with_suffix('.env.backup')
            import shutil
            shutil.copy2(env_path, backup_path)
        
        try:
            with open(env_path, 'w') as f:
                f.write("# OpenCode Environment Configuration\n")
                f.write(f"# Generated by Environment Manager\n\n")
                
                # Group related settings
                groups = {
                    "User Configuration": ["USER_ID", "GROUP_ID", "TIMEZONE"],
                    "Container Configuration": ["CONTAINER_NAME", "HOSTNAME"],
                    "Network Configuration": ["NETWORK_NAME"],
                    "Volume Configuration": [
                        "WORKSPACE_DIR", "GLOBAL_CONFIG", "PROJECT_CONFIG",
                        "OPENCODE_ENV_CONFIG", "WORKTREE_DIR"
                    ],
                    "Volume Mount Control": [
                        "MOUNT_GLOBAL_CONFIG", "MOUNT_PROJECT_CONFIG",
                        "MOUNT_OPENCODE_ENV_CONFIG"
                    ],
                    "Server Configuration": [
                        "OPENCODE_SERVER_ENABLED", "OPENCODE_SERVER_HOST",
                        "OPENCODE_SERVER_PORT", "OPENCODE_SERVER_USERNAME",
                        "OPENCODE_SERVER_PASSWORD", "OPENCODE_SERVER_CORS"
                    ],
                    "Resource Limits": ["MEMORY_LIMIT", "CPU_LIMIT", "SHM_SIZE"],
                }
                
                for group_name, keys in groups.items():
                    f.write(f"# {group_name}\n")
                    for key in keys:
                        if key in config:
                            value = config[key]
                            f.write(f"{key}={value}\n")
                    f.write("\n")
                
                # Write any remaining keys not in groups
                written_keys = set()
                for keys in groups.values():
                    written_keys.update(keys)
                
                remaining = {k: v for k, v in config.items() if k not in written_keys}
                if remaining:
                    f.write("# Additional Configuration\n")
                    for key, value in remaining.items():
                        f.write(f"{key}={value}\n")
        
        except Exception as e:
            raise ConfigurationError(f"Failed to write {env_path}: {e}")
    
    @staticmethod
    def get_bool_value(config: Dict[str, Any], key: str, default: bool = False) -> bool:
        """Get boolean value from config"""
        value = config.get(key, "")
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            return value.lower() in ("true", "yes", "1", "on")
        return default
    
    @staticmethod
    def get_int_value(config: Dict[str, Any], key: str, default: Optional[int] = None) -> Optional[int]:
        """Get integer value from config"""
        value = config.get(key)
        if value is None:
            return default
        try:
            return int(value)
        except (ValueError, TypeError):
            return default
    
    @staticmethod
    def get_str_value(config: Dict[str, Any], key: str, default: str = "") -> str:
        """Get string value from config"""
        value = config.get(key)
        return str(value) if value is not None else default
